P8105: Homework 2
================
Alexander Melamed

``` r
library(tidyverse)
```

    ## -- Attaching packages ------------------------------ tidyverse 1.3.0 --

    ## v ggplot2 3.3.2     v purrr   0.3.4
    ## v tibble  3.0.3     v dplyr   1.0.2
    ## v tidyr   1.1.2     v stringr 1.4.0
    ## v readr   1.3.1     v forcats 0.5.0

    ## -- Conflicts --------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

# Problem 1

The first part of this problem is to import and clean the Mr. Trash
Wheel data and to clean it.

``` r
trash_df = 
  readxl::read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
                     sheet="Mr. Trash Wheel", 
    range ="A2:N406") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(sports_balls=as.integer(sports_balls)
  )
trash_df
```

    ## # A tibble: 344 x 14
    ##    dumpster month  year date                weight_tons volume_cubic_ya~
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>            <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31               18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74               13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45               15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06               18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71               13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52               14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76               18
    ## # ... with 334 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <int>,
    ## #   homes_powered <dbl>

The next part of this problem is to read and clean precipitation data
for 2017 and 2018. For each, I omit rows without precipitation data and
add a variable year.

``` r
##Import and clean 2017 & 2018 data
precipitation_2017_df = 
  readxl::read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet="2017 Precipitation", range ="A2:B14") %>%
  janitor::clean_names() %>% 
  mutate(year=2017)

precipitation_2017_df
```

    ## # A tibble: 12 x 3
    ##    month total  year
    ##    <dbl> <dbl> <dbl>
    ##  1     1  2.34  2017
    ##  2     2  1.46  2017
    ##  3     3  3.57  2017
    ##  4     4  3.99  2017
    ##  5     5  5.64  2017
    ##  6     6  1.4   2017
    ##  7     7  7.09  2017
    ##  8     8  4.44  2017
    ##  9     9  1.95  2017
    ## 10    10  0     2017
    ## 11    11  0.11  2017
    ## 12    12  0.94  2017

``` r
##Import and clean 2018 data
precipitation_2018_df = 
  readxl::read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
                     sheet="2018 Precipitation", 
    range ="A2:B14") %>%
  janitor::clean_names() %>% 
  mutate(year=2018)

precipitation_2018_df
```

    ## # A tibble: 12 x 3
    ##    month total  year
    ##    <dbl> <dbl> <dbl>
    ##  1     1  0.94  2018
    ##  2     2  4.8   2018
    ##  3     3  2.69  2018
    ##  4     4  4.69  2018
    ##  5     5  9.27  2018
    ##  6     6  4.77  2018
    ##  7     7 10.2   2018
    ##  8     8  6.45  2018
    ##  9     9 10.5   2018
    ## 10    10  2.12  2018
    ## 11    11  7.82  2018
    ## 12    12  6.11  2018

Next, I combine precipitation datasets for 2017 and 2018 using
`bind_rows` and convert month to a character variable with `month.name`.
I also create a data set with only the 2017 Mr. Trash Wheel data,
because we’ll need it later on in this problem.

``` r
precipitation_2017_2018_df=
  bind_rows(precipitation_2017_df,precipitation_2018_df) %>% 
  mutate(month=month.name[month])


precipitation_2017_2018_df
```

    ## # A tibble: 24 x 3
    ##    month     total  year
    ##    <chr>     <dbl> <dbl>
    ##  1 January    2.34  2017
    ##  2 February   1.46  2017
    ##  3 March      3.57  2017
    ##  4 April      3.99  2017
    ##  5 May        5.64  2017
    ##  6 June       1.4   2017
    ##  7 July       7.09  2017
    ##  8 August     4.44  2017
    ##  9 September  1.95  2017
    ## 10 October    0     2017
    ## # ... with 14 more rows

The data frame `trash_df`, our read in and cleaned version of “Mr. Trash
Wheel” includes the following variables: dumpster, month, year, date,
weight\_tons, volume\_cubic\_yards, plastic\_bottles, polystyrene,
cigarette\_butts, glass\_bottles, grocery\_bags, chip\_bags,
sports\_balls, homes\_powered. The data has 344 observations. The data
frame `precipitation_2017_2018_df` combines precipitation data from 2017
and 2018. This data frame includes the following variables: month,
total, year.

I can use these data to calculate this like the total precipitation in
2018, which was 70.33 inches, or that the median median number of sports
balls in a dumpster in 2017 was 8.

## Problem 2

In the following code chunk I read and clean the data, and retain line,
station, name, station latitude / longitude, routes served, entry,
vending, entrance type, and ADA compliance. I convert the entry variable
from character (YES vs NO) to a logical variable (the ifelse or recode
function may be useful).

``` r
train_df=
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line,entry,vending,entrance_type,starts_with("station"),starts_with("route"), ada) %>% 
  select(!station_location) %>% 
  mutate(entry=if_else(entry=="NO",FALSE,TRUE))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
train_df
```

    ## # A tibble: 1,868 x 19
    ##    line  entry vending entrance_type station_name station_latitude
    ##    <chr> <lgl> <chr>   <chr>         <chr>                   <dbl>
    ##  1 4 Av~ TRUE  YES     Stair         25th St                  40.7
    ##  2 4 Av~ TRUE  YES     Stair         25th St                  40.7
    ##  3 4 Av~ TRUE  YES     Stair         36th St                  40.7
    ##  4 4 Av~ TRUE  YES     Stair         36th St                  40.7
    ##  5 4 Av~ TRUE  YES     Stair         36th St                  40.7
    ##  6 4 Av~ TRUE  YES     Stair         45th St                  40.6
    ##  7 4 Av~ TRUE  YES     Stair         45th St                  40.6
    ##  8 4 Av~ TRUE  YES     Stair         45th St                  40.6
    ##  9 4 Av~ TRUE  YES     Stair         45th St                  40.6
    ## 10 4 Av~ TRUE  YES     Stair         53rd St                  40.6
    ## # ... with 1,858 more rows, and 13 more variables: station_longitude <dbl>,
    ## #   route1 <chr>, route2 <chr>, route3 <chr>, route4 <chr>, route5 <chr>,
    ## #   route6 <chr>, route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, ada <lgl>

The dataset `train_df` includes the following variables: line, entry,
vending, entrance\_type, station\_name, station\_latitude,
station\_longitude, route1, route2, route3, route4, route5, route6,
route7, route8, route9, route10, route11, ada. To clean this data I
impored the raw data from the excel file
“NYC\_Transit\_Subway\_Entrance\_And\_Exit\_Data.csv”, used the
`janitorr::clean_name` function to harmonize naming conventions,
selelected the desired variables using the `select` function, and used
the `mutate` and `ifelse` function to recode entry as a logical vector.
The resulting dataframe has 1868 rows and 19 columns. I do not think
these data are tidy because the route variables to express different
information for different egressess. A Tidy data would have a series of
dummy variables for each train line.

There are 456 distinct stations. I couldn’t figure out how to use inline
code to calculate the number of distinct ADA copliant stations. Instead
I created a new data from that included only ADA compliant stations:

``` r
train_ada_df = train_df %>% 
  filter(ada=="TRUE")
```

Then I use the same inline code to figure out that there are 79 distinct
ADA compliant stations.

To figure out what proportion of station entrances / exits without
vending allow entrance, I create a data frame that only includes station
without vending:

``` r
train_noexit = train_df %>% 
  filter(vending!="YES")
```

and use inline code to calculated that 38% of these entrance/exits allow
enty.

In the next code chuck I reformat data so that route number and route
name are distinct variables. First I have to make all the route
variables character variables (because 8-11 were doubles). Then I use
`pivot_longer` to reshape the data from wide to long. Finally, I drop
all egresses that are not at station servicing the A line.

``` r
train_df_long=train_df %>% 
  mutate(route8=as.character(route8)) %>% 
  mutate(route9=as.character(route9)) %>% 
  mutate(route10=as.character(route10)) %>% 
  mutate(route11=as.character(route11)) %>% 
    pivot_longer(
      route1:route11,
      names_to = "Line",
      values_to ="route",
      names_prefix = "route") %>%
  filter(route=="A")
```

The following 56 unique stations serve the A train:

``` r
unique(train_df_long$station_name)
```

    ##  [1] "Times Square"                    "125th St"                       
    ##  [3] "145th St"                        "14th St"                        
    ##  [5] "168th St - Washington Heights"   "175th St"                       
    ##  [7] "181st St"                        "190th St"                       
    ##  [9] "34th St"                         "42nd St"                        
    ## [11] "59th St"                         "Broadway-Nassau"                
    ## [13] "Canal St"                        "Chambers St"                    
    ## [15] "Dyckman St-200th St"             "High St"                        
    ## [17] "Inwood - 207th St"               "West 4th St"                    
    ## [19] "World Trade Center"              "Lawrence St"                    
    ## [21] "Times Square-42nd St"            "168th St"                       
    ## [23] "59th St-Columbus Circle"         "8th Av"                         
    ## [25] "Fulton St"                       "Park Place"                     
    ## [27] "Franklin Av"                     "Broadway Junction-East New York"
    ## [29] "Euclid Av"                       "Hoyt & Schermerhorn"            
    ## [31] "Jay St - Borough Hall"           "Kingston-Throop"                
    ## [33] "Liberty Av"                      "Nostrand Av"                    
    ## [35] "Ralph Av"                        "Rockaway Av"                    
    ## [37] "Shepherd Av"                     "Utica Av"                       
    ## [39] "Van Siclen Av"                   "104th St-Oxford Av"             
    ## [41] "111th St-Greenwood Av"           "80th St-Hudson St"              
    ## [43] "88th St-Boyd Av"                 "Grant Av"                       
    ## [45] "Lefferts Blvd"                   "Rockaway Blvd"                  
    ## [47] "Aqueduct Racetrack"              "Aqueduct-North Conduit Av"      
    ## [49] "Beach 25th St"                   "Beach 36th St"                  
    ## [51] "Beach 44th St"                   "Beach 60th St"                  
    ## [53] "Beach 67th St"                   "Broad Channel"                  
    ## [55] "Far Rockaway-Mott Av"            "Howard Beach"

Of these, 16 are ADA compliant.

## Problem 3

First, clean the data in pols-month.csv. Use separate() to break up the
variable mon into integer variables year, month, and day; replace month
number with month name; create a president variable taking values gop
and dem, and remove prez\_dem and prez\_gop; and remove the day
variable.

``` r
library(readr)
pols_month <- read_csv(
  "data/fivethirtyeight_datasets/pols-month.csv") %>% 
  separate(mon,c("year","month","day")) %>% 
  mutate(month=as.numeric(month)) %>% 
  mutate(month=month.name[month]) %>% 
  mutate(year=as.numeric(year)) %>% 
  mutate(president=ifelse(prez_gop==0,"dem","gop")) %>% 
  select(-c(prez_dem,prez_gop,day))
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )

``` r
pols_month
```

    ## # A tibble: 822 x 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <dbl> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # ... with 812 more rows

Second, clean the data in snp.csv using a similar process to the above.
For consistency across datasets, arrange according to year and month,
and organize so that year and month are the leading columns.

``` r
snp <- read_csv("data/fivethirtyeight_datasets/snp.csv")  %>% separate(date,c("month","day","year")) %>% 
  mutate(month=as.numeric(month)) %>% 
  mutate(month=month.name[month]) %>% 
  mutate(year=as.numeric(year)) %>% 
  select(-day) %>% 
  arrange(year,month) %>% 
  relocate(year)
```

    ## Parsed with column specification:
    ## cols(
    ##   date = col_character(),
    ##   close = col_double()
    ## )

``` r
snp
```

    ## # A tibble: 787 x 3
    ##     year month    close
    ##    <dbl> <chr>    <dbl>
    ##  1  1950 April     18.0
    ##  2  1950 August    18.4
    ##  3  1950 December  20.4
    ##  4  1950 February  17.2
    ##  5  1950 January   17.0
    ##  6  1950 July      17.8
    ##  7  1950 June      17.7
    ##  8  1950 March     17.3
    ##  9  1950 May       18.8
    ## 10  1950 November  19.5
    ## # ... with 777 more rows

Third, tidy the unemployment data so that it can be merged with the
previous datasets. This process will involve switching from “wide” to
“long” format; ensuring that key variables have the same name; and
ensuring that key variables take the same values.

\<\<\<\<\<\<\< HEAD

``` r
unemployment <- read_csv("data/fivethirtyeight_datasets/unemployment.csv") %>% 
  pivot_longer(
      !Year,
      names_to = "month",
      values_to ="unemployment_rate") %>% 
  rename(year = Year) %>% 
  mutate(month=match(month,month.abb)) %>% 
  mutate(month=month.name[month]) 
```

    ## Parsed with column specification:
    ## cols(
    ##   Year = col_double(),
    ##   Jan = col_double(),
    ##   Feb = col_double(),
    ##   Mar = col_double(),
    ##   Apr = col_double(),
    ##   May = col_double(),
    ##   Jun = col_double(),
    ##   Jul = col_double(),
    ##   Aug = col_double(),
    ##   Sep = col_double(),
    ##   Oct = col_double(),
    ##   Nov = col_double(),
    ##   Dec = col_double()
    ## )

``` r
View(unemployment)
```

Join the datasets by merging snp into pols, and merging unemployment
into the result.

``` r
five35_merge=
  left_join(snp, pols_month) %>% 
  left_join(unemployment)
```

    ## Joining, by = c("year", "month")
    ## Joining, by = c("year", "month")
